version: '3.8'

services:
  django:
    build:
      context: ./backend
    container_name: django
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - DJANGO_SETTINGS_MODULE=myproject.settings
    depends_on:
      - db

  nextjs:
    build:
      context: ./path-to-nextjs-project
    container_name: nextjs
    ports:
      - "3000:3000"
    depends_on:
      - django

  db:
    image: postgres:13
    container_name: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword

volumes:
  pg_data:
